# Generated by Django 4.0 on 2021-12-08 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('funcionarios', '0001_initial'),
        ('exames', '0001_initial'),
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultamodel',
            name='exames',
            field=models.ManyToManyField(to='exames.ExameModel'),
        ),
        migrations.AddField(
            model_name='consultamodel',
            name='medicos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='funcionarios.funcionario'),
        ),
        migrations.AddField(
            model_name='consultamodel',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pacientes.paciente'),
        ),
    ]
