# Generated by Django 4.0 on 2021-12-08 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=500)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='funcionarios.funcionario')),
            ],
        ),
    ]
